---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1xk66639w57zrfhhsu32urvqeucvpesztzkl8g0a8ulvalcer9ezq530mrc"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1xk66639w57zrfhhsu32urvqeucvpesztzkl8g0a8ulvalcer9ezq530mrc"
  # https://github.com/ansible-collections/community.sops/issues/153
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age1xk66639w57zrfhhsu32urvqeucvpesztzkl8g0a8ulvalcer9ezq530mrc"
