apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:bpWHMI8Z4gpmvjPlTZromAU=,iv:YnGjsvUqP1HSp1uWX+anzL7oRAg+WZMR3kNd4u33Cic=,tag:O7XNiSur34AwYjssMGoD2g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/hXEAftqXrnhDmUHkd41+WvQTbB8GK4dNfntwMFVWTRHg3Qg,iv:/136w92dH6DVcdkXpyarV+n8zJHHyv7i2EKpkBsTrco=,tag:PxJfmFbBDXUHcM5DPtkBdg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:MCX5k5BsAgARw6Pbdic8,iv:bbJPLErfsaWYUJqxZBGywutKBQQmi2W8W4eDF0fzunY=,tag:D2s+3nRQKDfXN2DyKM0qKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xk66639w57zrfhhsu32urvqeucvpesztzkl8g0a8ulvalcer9ezq530mrc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZTJLbUtnN3NzR3JoQzZs
            aUNRTDBMckRTQmxDR1RDYmY2WU9PWWF4VmxNCnkvWUJhYmw4V2MzdXhEYnpud0dh
            WCsyNkRIaERzSU5sSFhKUk5ITXhkZ1UKLS0tIDB2bElweWVUeWhVR0ZldUtuSFJp
            OFVUY3FwaUdhVnhzNkpTV2QxUzNjMGsKMxo7wWZTbVfIiN4hkPH0e9rKRcDDQEvu
            UWmdLcM7NXt99YgBxZsPyA317gHgkqhJf/oBYU9YqWBxYmS299NHnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T22:54:49Z"
    mac: ENC[AES256_GCM,data:csO17YTgY9wr+3/QywSc8l9vc4rkUu83yNTIoH8b7/sKrj/1jTw3bIJ6TjxdfB4qXwo70o1lqsH+czZcStmJcM5NTdB5toYn4lv7Z+wrDb5yG2c1QuhF/X5GUS8DefNeZnGrQVL0Fu7kqMlgrmgEL7QpZDWBQqGL6rhIIRUp/i0=,iv:n23htiaYXYZye7AHZfN2FJ20nlfX0vWixQ0tVZlF6Dg=,tag:i0bv4xF1kOug3xlM/T2mTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
