apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:eHvTASduJQPvKPKhjZByBKtdTd9suiqIbKXHM3AcQaSXMbR0,iv:tQup5fnZC/Y/ch4B5EaD2cRC4QRUOnIr2tcXCoMC1IY=,tag:7HjyaSmlaZ3T68pSXcxl1g==,type:str]
    credentials.json: ENC[AES256_GCM,data:WPejBQKUCUJ0crCY8ToEQILIphQy4Ax2QusLvjcJeJqBRxxvQYugm2TYYaRrLXhDN2DTn3vuL9NIM5yFw+oz5Jbtsn3AwTYHvHRr0QOXo1uNFXIllEdL9ILdSY/PlaLRwecD19NrjBevHIcjchYXw0+PfxXwcDzfabOj6SJGZ5l6wgYwyiYcYISWKCAe5eL5jStwZqv+aSKd7m4K1EhuPfh+TjyIowTmL+VA3JvVOQ==,iv:NaPKOKfwZV3PsLoBcLilkjJ7ZGRz5bRxclQrTrIpAJQ=,tag:pkgaqAeAKVnou+AXOHgAJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xk66639w57zrfhhsu32urvqeucvpesztzkl8g0a8ulvalcer9ezq530mrc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOGZkT0dEUFNkTmpxOFNE
            UTZwZUZVMUlpLzhsL2xaVkJ1K1VpZWREUHdzCkJGTjh4NkFyZi82LzEyQWtWNW11
            a3ZESDRickpOMXBhSWhJMVhkNU5HUUUKLS0tIDV2Z25nQTdqb2dIWWpOTGZsVStV
            UnpXQWtnc2o4a1FmOUVheVZ0emNvTkEKqhU7Bhce8sr2Ivk/Bjrj0UOAmLdusTZG
            pQQze5yY4Tb0zHh9Eqrn319tLwPy3bqKPMeMJa8D9EdFiBUi1mSYWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T22:54:51Z"
    mac: ENC[AES256_GCM,data:dZ1ri/j2rKCOUv2CUbqU6EAXWPVJFGiJpSgGZL1SgJrHdUgwz46ZmW0JOLCtfI3dZAf3LRal5vBVxvCxIfXa5AT1i2juTH94arf9QzfEjZsKaJjedcd7M8tfzaEVuh3u1um97VINPFj34TbdCW0AZ0/RJplyFlHpWrDZh+mZq18=,iv:Vzh5H0V0vT2rIwrQeK4FzGMC+XvhHSii6ivLMkSxfu0=,tag:MbC1f5DOLeJq19LidU6DuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
