apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:0ry5GqpeC78rUEEZsKDNmlLJkAiov7b76ruvkGQQZLsF0PgV,iv:xDN6SkQHpROlmomeX+J6lBuOpOhO5SFAxojNX6cuIjo=,tag:bAV+Xs/ADsB6POrs7jBMXw==,type:str]
    credentials.json: ENC[AES256_GCM,data:0qjfb8a6QIgtjPhUdDsbGDORMJZt1asADFA112SL0teKcQdvo3UfudnRJmCMrfAjC+v/jholyDK+IviH4RfEK5bvSrZU7wCkWlUyuLw8GE9ULNsluV55+TCS5ImyleALKgyfmM9T462FXrVuXE/CVJvxxGsL5IEBrlH8+CcIGfEkLC31PJyjSSMjAQBCys/Br61YjzQQsIreGhHcbA2QFb++2Oet4oRPyZu/3nOqHA==,iv:bIsMpVYBi68yqxUJt9Y/RYSDPUlKG3+KCR1oodA+qPc=,tag:dB/YHJlaZzaFePb1lEh4XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xk66639w57zrfhhsu32urvqeucvpesztzkl8g0a8ulvalcer9ezq530mrc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRLy9OMktMUkV4TWJGUUlD
            Ym9pRnpuRmxKV3RHdUFSR1BDUGFKWTR5R3dVCnJIcDNia1kxaHloYnpWSllQdU14
            S1FTdkxucjZLVWhiQ3l1anZFaDRybHMKLS0tIFJzTjRZNTM0TzQ4VFlGYnNTZjBn
            RjI5OC95eFRDb3UyY2dBNjBDTXNkLzgKrG48RcbH20swQ+QYoklrSrRpvpvCq5lX
            W6bSgx+9SKUTRHU+dVveAO3WmRePxJHf+ESDPY3cS6e2kDLTdIbz6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-05T02:19:19Z"
    mac: ENC[AES256_GCM,data:0E7pM4KqwORckN/c43/jj0FL+cRBscKOF4+dlO6GykL90lLFWedHRA3oMbMbN2cgBf6pP2Tbu9L0cH9k8es/cFGzVgLfSrHyuePxYDm4ziSQCrbJWS/+Q1eOgvWYznI9XjLFD1hQ+u9pegcf4D22QhhzXqwNQ+eVtg1r0x/dF9Q=,iv:nscIE2WrrNcLNMNwvH0TgAWqiD7GaHKrLye3sUbVpd4=,tag:DestyChyGG/6XNyqJudD/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
